const majorCodes = {
  data: [
    { code: '0000', description: 'Non-Matriculated' },
    { code: '0056', description: 'Undecided Major and College' },
    { code: '00UH', description: 'Honors' },
    { code: '00US', description: 'University Studies' },
    { code: '349', description: 'Office Administration' },
    { code: '370', description: 'Library/Media Tech Assistance' },
    { code: '380', description: 'Pulp and Paper Technology' },
    { code: '387', description: 'Criminal Justice Studies' },
    { code: '3AE', description: 'Secretarial Science' },
    { code: '3LE', description: 'Automotive Technology' },
    { code: '3LG', description: 'Drafting-Design Technology' },
    { code: '3LL', description: 'Climate Control Technology' },
    { code: '3PF', description: 'Electromechancial EGR Tech' },
    { code: '3PH', description: 'Manufacturing/Indust EGR Teh' },
    { code: '3PM', description: 'Metallurigical EGR Technology' },
    { code: '3PN', description: 'Manufacturing Technology 2 YR' },
    { code: '3QT', description: 'Computer Tech:  Transfer Opt' },
    { code: 'A02', description: 'Aeronautics' },
    { code: 'A47', description: 'Business Psychology' },
    { code: 'A53', description: 'Communication & Theatre' },
    { code: 'A58', description: 'Aeronautics-Mathematics' },
    { code: 'A64', description: 'Mineralogy' },
    { code: 'A80', description: 'Pulp and Paper Technology' },
    { code: 'A87', description: 'Criminal Justice Studies' },
    { code: 'A92', description: 'Medical Technology' },
    { code: 'AAA', description: 'Psychology/Type 3/Business' },
    { code: 'AEP', description: 'Pre-Engineering Physics' },
    { code: 'AIW', description: 'English:  Professional Writing' },
    { code: 'AJC', description: 'Speech Pathology' },
    { code: 'ALS', description: 'English:  Communication (Ed)' },
    { code: 'AMT', description: 'Medical Technology' },
    { code: 'AP08', description: 'Entrepreneurship' },
    { code: 'AP1C', description: 'Computer Aided Drafting/Mfg' },
    { code: 'AP27', description: 'Electrical & Computer Engineer' },
    { code: 'AP2C', description: 'Computer Hardware Technology' },
    { code: 'AP3C', description: 'Paper Science and Engineering' },
    { code: 'AP49', description: 'Global & Intercultural Studies' },
    { code: 'AP4C', description: 'Leadership' },
    { code: 'AP53', description: 'Art Therapy' },
    { code: 'AP56', description: 'Undeclared - Applied Science' },
    { code: 'AP5C', description: 'Adv Manufacturing & Mater Eval' },
    { code: 'AP61', description: 'Food Systems and Food Studies' },
    { code: 'AP71', description: 'Nursing - 2 Year' },
    { code: 'AP72', description: 'Paper Science & Engineering' },
    { code: 'AP84', description: 'Manufacturing Engineering' },
    { code: 'AP87', description: 'Computer and Information Techn' },
    { code: 'AP88', description: 'Computer Technology' },
    { code: 'AP89', description: 'Systems Analysis' },
    { code: 'AP90', description: 'Computer Science' },
    { code: 'APAM', description: 'Arts Management' },
    { code: 'APAN', description: 'Analytics' },
    { code: 'APBE', description: 'Bioengineering' },
    { code: 'APBX', description: 'Biomedical Engineering' },
    { code: 'APCB', description: 'Chemical & Biomedical Engineer' },
    { code: 'APCC', description: 'Crit & Classic Lang & Cultures' },
    { code: 'APCE', description: 'Computer Engineering' },
    { code: 'APCH', description: 'Chemical Technology' },
    { code: 'APCL', description: 'Chemical Engineering' },
    { code: 'APCM', description: 'Comparative Media Studies' },
    { code: 'APCO', description: 'Computatn Mechanical Engineer' },
    { code: 'APCS', description: 'Computational Sci and Engineer' },
    { code: 'APEC', description: 'Computatn Elec & Comp Engineer' },
    { code: 'APEE', description: 'Electrical Engineering' },
    { code: 'APEN', description: 'Energy' },
    { code: 'APEP', description: 'Environ Principles & Practices' },
    { code: 'APES', description: 'Environmental Science' },
    { code: 'APET', description: 'Engineering Technology' },
    { code: 'APFC', description: 'Film Studies' },
    { code: 'APFN', description: 'Fashion' },
    { code: 'APGE', description: 'General Engineering' },
    { code: 'APHT', description: 'Health Information Technology' },
    { code: 'APIM', description: 'Interactive Media Studies' },
    { code: 'APME', description: 'Mechanical Engineering' },
    { code: 'APN4', description: 'Nursing' },
    { code: 'APNS', description: 'Neuroscience' },
    { code: 'APPC', description: 'Mechanical Engineering Tech' },
    { code: 'APPE', description: 'Electrical Engineering Tech' },
    { code: 'APPM', description: 'Premedical Studies' },
    { code: 'APPR', description: 'Nursing - 4 Year' },
    { code: 'APPZ', description: 'Electrical & Computer Eng Tech' },
    { code: 'APQV', description: 'Engineering Management' },
    { code: 'APRE', description: 'Robotics Engineering' },
    { code: 'APRT', description: 'Radiologic Technology' },
    { code: 'APSE', description: 'Software Engineering' },
    { code: 'APSU', description: 'Sustainability' },
    { code: 'APTS', description: 'Technical Study' },
    { code: 'APZ1', description: 'Applied Science - AA' },
    { code: 'APZ2', description: 'Engineering and Computing - AA' },
    { code: 'AS02', description: 'Aeronautics' },
    { code: 'AS05', description: 'Microbiology' },
    { code: 'AS06', description: 'Anthropology' },
    { code: 'AS07', description: 'Botany' },
    { code: 'AS08', description: 'Entrepreneurship' },
    { code: 'AS09', description: 'Chemistry' },
    { code: 'AS11', description: 'Classical Humanities' },
    { code: 'AS12', description: 'American Studies' },
    { code: 'AS15', description: 'Economics' },
    { code: 'AS18', description: 'English:  Literature' },
    { code: 'AS1C', description: 'Geographic Information Science' },
    { code: 'AS20', description: 'Diplomacy and Foreign Affairs' },
    { code: 'AS21', description: 'French' },
    { code: 'AS22', description: 'Geography & Sustainable Dvlpmt' },
    { code: 'AS23', description: 'Geography' },
    { code: 'AS24', description: 'Geology' },
    { code: 'AS25', description: 'German' },
    { code: 'AS26', description: 'Political Science' },
    { code: 'AS27', description: 'Greek' },
    { code: 'AS29', description: 'History' },
    { code: 'AS2C', description: 'Global Readiness' },
    { code: 'AS35', description: 'Latin' },
    { code: 'AS37', description: 'Mathematics & Statistics' },
    { code: 'AS42', description: 'Philosophy' },
    { code: 'AS45', description: 'Physics' },
    { code: 'AS46', description: 'Biological Science' },
    { code: 'AS47', description: 'Psychology' },
    { code: 'AS49', description: 'Global & Intercultural Studies' },
    { code: 'AS51', description: 'Sociology' },
    { code: 'AS52', description: 'Spanish' },
    { code: 'AS53', description: 'Art Therapy' },
    { code: 'AS55', description: 'Zoology' },
    { code: 'AS56', description: 'Undeclared - Arts & Science' },
    { code: 'AS58', description: 'Aeronautics-Mathematics' },
    { code: 'AS59', description: 'International Studies' },
    { code: 'AS61', description: 'Food Systems and Food Studies' },
    { code: 'AS65', description: 'Public Administration' },
    { code: 'AS66', description: 'Religion' },
    { code: 'AS68', description: 'Engineering Physics' },
    { code: 'AS69', description: 'Mass Communication' },
    { code: 'AS72', description: 'Paper Science & Engineering' },
    { code: 'AS74', description: 'Russian' },
    { code: 'AS75', description: 'Black World Studies' },
    { code: 'AS76', description: 'Environmental Science' },
    { code: 'AS86', description: 'Theatre' },
    { code: 'AS92', description: 'Clinical Laboratory Science' },
    { code: 'AS94', description: 'Urban and Regional Planning' },
    { code: 'AS97', description: 'Educational Administration' },
    { code: 'ASAL', description: 'East Asian Languages & Culture' },
    { code: 'ASAM', description: 'Arts Management' },
    { code: 'ASAN', description: 'Analytics' },
    { code: 'ASBC', description: 'Biochemistry' },
    { code: 'ASBI', description: 'Biology' },
    { code: 'ASBP', description: 'Biological Physics' },
    { code: 'ASCB', description: 'Cell, Molec & Struct Biology' },
    { code: 'ASCC', description: 'Crit & Classic Lang & Cultures' },
    { code: 'ASCH', description: 'Chemical Technology' },
    { code: 'ASCJ', description: 'Criminal Justice' },
    { code: 'ASCL', description: 'Classical Languages' },
    { code: 'ASCM', description: 'Comparative Media Studies' },
    { code: 'ASCP', description: 'Communication Pre-Major' },
    { code: 'ASCR', description: 'Critical Race & Ethnic Studies' },
    { code: 'ASCS', description: 'Classical Studies' },
    { code: 'ASDA', description: 'Data Analytics' },
    { code: 'ASDP', description: 'Diplomacy and Global Politics' },
    { code: 'ASDS', description: 'Data Science and Statistics' },
    { code: 'ASEA', description: 'Earth Science' },
    { code: 'ASEE', description: 'Ecol, Evol & Envir Biology' },
    { code: 'ASEN', description: 'Energy' },
    { code: 'ASEP', description: 'Environ Principles & Practices' },
    { code: 'ASES', description: 'Environmental Science' },
    { code: 'ASEV', description: 'Environmental Earth Science' },
    { code: 'ASFC', description: 'Film Studies' },
    { code: 'ASFN', description: 'Fashion' },
    { code: 'ASGE', description: 'Gerontology' },
    { code: 'ASHG', description: 'Gerontological Studies' },
    { code: 'ASIA', description: 'English' },
    { code: 'ASIB', description: 'Linguistics' },
    { code: 'ASIC', description: 'English:  Creative Writing' },
    { code: 'ASIE', description: 'English Lit: Teacher Cert' },
    { code: 'ASIG', description: 'Tech & Scientific Comm' },
    { code: 'ASII', description: 'Mathematics' },
    { code: 'ASIJ', description: 'English:  Journalism' },
    { code: 'ASIL', description: 'English:  Linguistics' },
    { code: 'ASIM', description: 'Interactive Media Studies' },
    { code: 'ASIN', description: 'Individualized Studies' },
    { code: 'ASIP', description: 'Statistics' },
    { code: 'ASIS', description: 'Italian Studies' },
    { code: 'ASJA', description: 'Music' },
    { code: 'ASJB', description: 'Speech Path & Audiology' },
    { code: 'ASJD', description: 'Speech-Language Pathology' },
    { code: 'ASJN', description: 'Journalism' },
    { code: 'ASLR', description: 'History of Art & Arc' },
    { code: 'ASLS', description: 'Latin American Studies' },
    { code: 'ASMC', description: 'Media and Culture' },
    { code: 'ASML', description: 'Medical Laboratory Science' },
    { code: 'ASNS', description: 'Neuroscience' },
    { code: 'ASOL', description: 'Organizational Leadership' },
    { code: 'ASPH', description: 'Public Health' },
    { code: 'ASPJ', description: 'Pre Journalism' },
    { code: 'ASPM', description: 'Premedical Studies' },
    { code: 'ASPS', description: 'Population and Social Gerontol' },
    { code: 'ASPW', description: 'Professional Writing' },
    { code: 'ASQE', description: 'Quantitative Economics' },
    { code: 'ASRE', description: 'Russian,East Eur & Eurasian St' },
    { code: 'ASRT', description: 'Radiologic Technology' },
    { code: 'ASSC', description: 'Speech Communication' },
    { code: 'ASSG', description: 'Social Gerontology' },
    { code: 'ASSJ', description: 'Social Justice Studies' },
    { code: 'ASST', description: 'Strategic Communication' },
    { code: 'ASSU', description: 'Sustainability' },
    { code: 'ASSW', description: 'Social Work' },
    { code: 'ASU1', description: 'University Studies' },
    { code: 'ASU2', description: 'University Studies' },
    { code: 'ASU3', description: 'University Studies' },
    { code: 'ASU4', description: 'University Studies' },
    { code: 'ASU5', description: 'University Studies' },
    { code: 'ASUS', description: 'University Studies' },
    { code: 'ASWG', description: 'Women,Gender&Sexuality Studies' },
    { code: 'ASWS', description: "Women's Studies" },
    { code: 'ASZ5', description: 'Humanities - AA' },
    { code: 'ASZ6', description: 'Natural Science - AA' },
    { code: 'ASZ7', description: 'Social Science - AA' },
    { code: 'ASZ8', description: 'Nat Sci  & Mathematics - AA' },
    { code: 'B33', description: 'Organizational Administration' },
    { code: 'B34', description: 'Organizational Administration' },
    { code: 'B41', description: 'Production & Decision Sciences' },
    { code: 'B60', description: 'Executive Secretarial Tech' },
    { code: 'BAB', description: 'Business Analysis' },
    { code: 'BAE', description: 'Secretarial Science' },
    { code: 'BAH', description: 'Personnel Management' },
    { code: 'BAI', description: 'Personnel & Employment Relatns' },
    { code: 'BKJ', description: 'Banking & Finance Technology' },
    { code: 'BKK', description: 'Insurance Technology' },
    { code: 'BKL', description: 'Bus Information Mgt Tech' },
    { code: 'BKN', description: 'Real Estate Technology' },
    { code: 'BKO', description: 'Personnel & Employ Relations' },
    { code: 'BKP', description: 'Production & Operations Mgt' },
    { code: 'BKQ', description: 'Purchasing Management' },
    { code: 'BKS', description: 'Production & Operations Mgt' },
    { code: 'BKT', description: 'Production & Decision Sciences' },
    { code: 'BU01', description: 'Accountancy' },
    { code: 'BU08', description: 'Entrepreneurship' },
    { code: 'BU14', description: 'Business Economics' },
    { code: 'BU15', description: 'Economics' },
    { code: 'BU19', description: 'Finance' },
    { code: 'BU1C', description: 'China Business Program' },
    { code: 'BU1D', description: 'Medical Office Management' },
    { code: 'BU22', description: 'General Business' },
    { code: 'BU2C', description: 'Banking' },
    { code: 'BU2D', description: 'Creativity Entrepreneurship' },
    { code: 'BU33', description: 'Organizational Behavior' },
    { code: 'BU34', description: 'Organizational Leadership' },
    { code: 'BU36', description: 'Marketing' },
    { code: 'BU3C', description: 'Business Info Software Tech' },
    { code: 'BU3D', description: 'StartUp Entrepreneurship' },
    { code: 'BU41', description: 'Decision Sciences' },
    { code: 'BU48', description: 'Office Management Technology' },
    { code: 'BU49', description: 'Global & Intercultural Studies' },
    { code: 'BU4C', description: 'Gen Secretarial Technical Pgm' },
    { code: 'BU4D', description: 'Social Entrepreneurship' },
    { code: 'BU50', description: 'Business Software Technology' },
    { code: 'BU53', description: 'Art Therapy' },
    { code: 'BU56', description: 'Undeclared - Business' },
    { code: 'BU5C', description: 'General Spv Technical Program' },
    { code: 'BU5D', description: 'Foundations of Analytics' },
    { code: 'BU61', description: 'Food Systems and Food Studies' },
    { code: 'BU6C', description: 'Small Bus Mgt Technology Pgm' },
    { code: 'BU6D', description: 'Business in the Global Market' },
    { code: 'BU7C', description: 'Small Office Mgt Technical Pgm' },
    { code: 'BU8C', description: 'Accounting Technology Program' },
    { code: 'BU9C', description: 'Records Management' },
    { code: 'BUAM', description: 'Arts Management' },
    { code: 'BUAN', description: 'Analytics' },
    { code: 'BUBA', description: 'Business Administration' },
    { code: 'BUBY', description: 'Business Analytics' },
    { code: 'BUCC', description: 'Crit & Classic Lang & Cultures' },
    { code: 'BUCM', description: 'Comparative Media Studies' },
    { code: 'BUEB', description: 'E-Business Management Tech' },
    { code: 'BUEN', description: 'Energy' },
    { code: 'BUEP', description: 'Environ Principles & Practices' },
    { code: 'BUES', description: 'Environmental Science' },
    { code: 'BUFC', description: 'Film Studies' },
    { code: 'BUFN', description: 'Fashion' },
    { code: 'BUGL', description: 'General' },
    { code: 'BUHC', description: 'Human Capital Mgmt& Leadership' },
    { code: 'BUIA', description: 'Information Systems &Analytics' },
    { code: 'BUIB', description: 'Interdisciplinary Bus Managemt' },
    { code: 'BUIM', description: 'Interactive Media Studies' },
    { code: 'BUIS', description: 'Information Systems' },
    { code: 'BUK3', description: 'Marketing Management Tech' },
    { code: 'BUKA', description: 'Accounting Technology' },
    { code: 'BUKM', description: 'Business Management Technology' },
    { code: 'BUKO', description: 'Human Resources Management' },
    { code: 'BUKP', description: 'Operations Management' },
    { code: 'BUKQ', description: 'Purchasing/Procurement Mgt' },
    { code: 'BUKR', description: 'Management' },
    { code: 'BUME', description: 'Managing Extended Enterprise' },
    { code: 'BUMK', description: 'Management Information Systems' },
    { code: 'BUML', description: 'Quality & Process Improvement' },
    { code: 'BUMN', description: 'Management and Leadership' },
    { code: 'BUMO', description: 'Management and Organizations' },
    { code: 'BUNS', description: 'Neuroscience' },
    { code: 'BUPM', description: 'Premedical Studies' },
    { code: 'BUSO', description: 'Supply Chain & Operations Mgmt' },
    { code: 'BUSP', description: 'Supply Chain Management' },
    { code: 'BUSU', description: 'Sustainability' },
    { code: 'BUZ2', description: 'Business - AA' },
    { code: 'C001', description: 'Analytics for Professionals' },
    { code: 'C002', description: 'Adult TESOL' },
    { code: 'C003', description: 'Advanced Studio Art' },
    { code: 'C004', description: 'Applied Statistics' },
    { code: 'C005', description: 'Assessment and Evaluation' },
    { code: 'C006', description: 'Autism Spectrum Disorders' },
    { code: 'C007', description: 'College Teaching' },
    { code: 'C008', description: 'Conservation Biology' },
    { code: 'C009', description: 'Ecology' },
    { code: 'C010', description: 'Geographic Information Science' },
    { code: 'C011', description: 'Human Brain and Learning' },
    { code: 'C012', description: 'Instructional Design' },
    { code: 'C013', description: 'Interactive Media Studies' },
    { code: 'C014', description: 'Quant Data Analysis in Edu&SS' },
    { code: 'C015', description: 'Russian,East Eur & Eurasian St' },
    { code: 'C016', description: 'Sport Management' },
    { code: 'C017', description: 'Sport Psychology' },
    { code: 'C018', description: 'Women,Gender&Sexuality Studies' },
    { code: 'C019', description: 'Gerontology; Soc Entr & Aging' },
    { code: 'C020', description: 'Criminal Justice Admin' },
    { code: 'C021', description: 'Analytics' },
    { code: 'C022', description: 'Advanced Business Analytics' },
    { code: 'C023', description: 'Business Management' },
    { code: 'C024', description: 'Esports Management' },
    { code: 'C025', description: 'Child Life Specialist' },
    { code: 'C026', description: 'Entrepreneurship&Emer Tech' },
    { code: 'C027', description: 'Adv Manufacturing & Mater Eval' },
    { code: 'E08', description: 'Business Education' },
    { code: 'E10', description: 'Aerospace Education' },
    { code: 'E13', description: 'Classroom Teacher, Elementary' },
    { code: 'E32', description: 'Industrial Education' },
    { code: 'E40', description: 'Guidance and Counseling' },
    { code: 'E44', description: 'Elementary School Principal' },
    { code: 'E54', description: 'Speech and Hearing Therapy' },
    { code: 'E61', description: 'Supt and Central Office Admin' },
    { code: 'E62', description: 'Secondary School Principal' },
    { code: 'E63', description: 'Diagnostic & Remedial Edu' },
    { code: 'E67', description: 'Diagnostic & Remedial Edu' },
    { code: 'E77', description: 'Library/Media Education' },
    { code: 'E78', description: 'Edu Mentally Handicapped/Elem' },
    { code: 'E79', description: 'Learn & Behavior Disorder/Elem' },
    { code: 'E81', description: 'College Student Personnel Serv' },
    { code: 'E82', description: 'College Student Personnel Serv' },
    { code: 'E91', description: 'Educational Media' },
    { code: 'E95', description: 'Science' },
    { code: 'EA02', description: 'Education Studies' },
    { code: 'EA08', description: 'Entrepreneurship' },
    { code: 'EA09', description: 'Chemistry' },
    { code: 'EA16', description: 'Secondary Education' },
    { code: 'EA17', description: 'Elementary Education' },
    { code: 'EA18', description: 'Adolescent Education' },
    { code: 'EA1C', description: 'Teaching English Lang Learners' },
    { code: 'EA21', description: 'French' },
    { code: 'EA25', description: 'German' },
    { code: 'EA28', description: 'Curriculum and Supervision' },
    { code: 'EA2C', description: 'Outdoor Leadership' },
    { code: 'EA30', description: 'Educational Psychology' },
    { code: 'EA31', description: 'Individual & Family Studies' },
    { code: 'EA35', description: 'Latin' },
    { code: 'EA3C', description: 'Autism Spectrum Disorders' },
    { code: 'EA43', description: 'Physical Education' },
    { code: 'EA45', description: 'Physics' },
    { code: 'EA46', description: 'Biological Science' },
    { code: 'EA49', description: 'Global & Intercultural Studies' },
    { code: 'EA4C', description: 'Fostering Just Communities' },
    { code: 'EA50', description: 'Reading Education' },
    { code: 'EA52', description: 'Spanish' },
    { code: 'EA53', description: 'Art Therapy' },
    { code: 'EA56', description: 'Undeclared - Education' },
    { code: 'EA5C', description: 'Child Life Specialist' },
    { code: 'EA61', description: 'Food Systems and Food Studies' },
    { code: 'EA67', description: 'Special Education' },
    { code: 'EA6C', description: 'Sport Analytics' },
    { code: 'EA73', description: 'School Psychology' },
    { code: 'EA74', description: 'Russian' },
    { code: 'EA81', description: 'College Student Personnel' },
    { code: 'EA83', description: 'Social Studies Education' },
    { code: 'EA93', description: 'Earth Science' },
    { code: 'EA96', description: 'Health Education' },
    { code: 'EA97', description: 'Educational Administration' },
    { code: 'EAAM', description: 'Arts Management' },
    { code: 'EAAN', description: 'Analytics' },
    { code: 'EACC', description: 'Crit & Classic Lang & Cultures' },
    { code: 'EACH', description: 'Chemistry Education' },
    { code: 'EACM', description: 'Comparative Media Studies' },
    { code: 'EACT', description: 'Curriculum & Tchr Leadership' },
    { code: 'EAEH', description: 'Exercise and Health Studies' },
    { code: 'EAEL', description: 'Educational Leadership' },
    { code: 'EAEN', description: 'Energy' },
    { code: 'EAEP', description: 'Environ Principles & Practices' },
    { code: 'EAES', description: 'Environmental Science' },
    { code: 'EAET', description: 'Educational Technology' },
    { code: 'EAEX', description: 'Exercise Science' },
    { code: 'EAFA', description: 'Family Science' },
    { code: 'EAFC', description: 'Film Studies' },
    { code: 'EAFE', description: 'Family Life Education' },
    { code: 'EAFL', description: 'Foreign Language Education' },
    { code: 'EAFN', description: 'Fashion' },
    { code: 'EAFS', description: 'Family Studies' },
    { code: 'EAGA', description: 'Early Childhood Education' },
    { code: 'EAGB', description: 'Earth Science Education' },
    { code: 'EAGC', description: 'Earth Science/Life Sci Edu' },
    { code: 'EAGD', description: 'Earth Science/Chemistry Edu' },
    { code: 'EAGE', description: 'Earth Science/Physics Edu' },
    { code: 'EAGF', description: 'Integrated Eng Lang Arts Edu' },
    { code: 'EAGG', description: 'Integrated Mathematics Edu' },
    { code: 'EAGJ', description: 'Integrated Social Studies Edu' },
    { code: 'EAGM', description: 'French Education' },
    { code: 'EAGN', description: 'German Education' },
    { code: 'EAGO', description: 'Latin Education' },
    { code: 'EAGP', description: 'Chinese Education' },
    { code: 'EAGQ', description: 'Spanish Education' },
    { code: 'EAGR', description: 'Life Science Education' },
    { code: 'EAGT', description: 'Life Science/Physics Education' },
    { code: 'EAGU', description: 'Physical Science Education' },
    { code: 'EAGV', description: 'Middle Childhood Education' },
    { code: 'EAGW', description: 'Special Education' },
    { code: 'EAGX', description: 'Speech Lang Path & Audiology' },
    { code: 'EAGZ', description: 'Inclusive Special Education' },
    { code: 'EAHH', description: 'Health Appraisal & Enhancement' },
    { code: 'EAHP', description: 'Health Promotion' },
    { code: 'EAHS', description: 'Health Studies' },
    { code: 'EAID', description: 'Instructional Desgn&Technology' },
    { code: 'EAII', description: 'Mathematics' },
    { code: 'EAIM', description: 'Interactive Media Studies' },
    { code: 'EAIS', description: 'Integrated Science Education' },
    { code: 'EAJ', description: 'Classroom Teacher, Secondary' },
    { code: 'EAJD', description: 'Speech/Language Pathology' },
    { code: 'EAK', description: 'Personnel Serv & Counseling' },
    { code: 'EAKH', description: 'Kinesiology and Health' },
    { code: 'EAKN', description: 'Kinesiology' },
    { code: 'EALC', description: 'Life Science/Chemistry Educ' },
    { code: 'EALF', description: 'English Education' },
    { code: 'EALH', description: 'Athletic Training' },
    { code: 'EALL', description: 'Literacy and Language' },
    { code: 'EALN', description: 'Health Education' },
    { code: 'EALQ', description: 'Family & Child Studies' },
    { code: 'EALV', description: 'Communication Education' },
    { code: 'EALZ', description: 'Physical Education' },
    { code: 'EAMA', description: 'Dietetics' },
    { code: 'EAME', description: 'Adolescent Mathematics Edu' },
    { code: 'EAMG', description: 'Elementary Mathematics Edu' },
    { code: 'EAMH', description: 'Recreation Educ & Programming' },
    { code: 'EAMJ', description: 'Retailing' },
    { code: 'EAMN', description: 'Elem/Kindergarten-Primary Ed' },
    { code: 'EAMP', description: 'Pre-Kindergarten Education' },
    { code: 'EAMS', description: 'Secondary Mathematics Edu' },
    { code: 'EANS', description: 'Neuroscience' },
    { code: 'EANU', description: 'Nutrition' },
    { code: 'EAP5', description: 'Primary Education PK-5' },
    { code: 'EAPH', description: 'Public Health' },
    { code: 'EAPK', description: 'Pre-Kindergarten' },
    { code: 'EAPM', description: 'Premedical Studies' },
    { code: 'EASA', description: 'Student Affairs in Higher Educ' },
    { code: 'EASL', description: 'School Leadership' },
    { code: 'EASM', description: 'Sport Leadership & Management' },
    { code: 'EASP', description: 'Sport Organization' },
    { code: 'EASR', description: 'Sport Studies' },
    { code: 'EASU', description: 'Sustainability' },
    { code: 'EASW', description: 'Social Work' },
    { code: 'EATL', description: 'Transformative Education' },
    { code: 'EAZ1', description: 'Education, Health&Society - AA' },
    { code: 'EAZ3', description: 'Education - AA' },
    { code: 'ECJ', description: 'Computer Science Education' },
    { code: 'EJB', description: 'COM--Speech Pathology & Audio' },
    { code: 'ELA', description: 'English:  Linguistics (Ed)' },
    { code: 'ELB', description: 'English:  Literature (Ed)' },
    { code: 'ELM', description: 'Speech Education' },
    { code: 'ELO', description: 'Health & Physical Education' },
    { code: 'ELP', description: 'Textiles and Clothing' },
    { code: 'ELT', description: 'Communications Edu:  Speech' },
    { code: 'ELU', description: 'Communications Edu:  English' },
    { code: 'ELX', description: 'Housing & Interior Design' },
    { code: 'ELY', description: 'Consumer Service' },
    { code: 'EMC', description: 'Home Economics Education' },
    { code: 'EMD', description: 'Food Management' },
    { code: 'EME', description: 'Food Service Management' },
    { code: 'FA03', description: 'Art' },
    { code: 'FA04', description: 'Art Education' },
    { code: 'FA05', description: 'Graphic Design' },
    { code: 'FA08', description: 'Entrepreneurship' },
    { code: 'FA1C', description: 'Design Thinking' },
    { code: 'FA21', description: 'Games + Simulation' },
    { code: 'FA2C', description: 'Esports Management' },
    { code: 'FA38', description: 'Music Performance' },
    { code: 'FA39', description: 'Music Education' },
    { code: 'FA49', description: 'Global & Intercultural Studies' },
    { code: 'FA53', description: 'Art Therapy' },
    { code: 'FA56', description: 'Major Undeclared' },
    { code: 'FA57', description: 'Environmental Design' },
    { code: 'FA61', description: 'Food Systems and Food Studies' },
    { code: 'FA86', description: 'Theatre' },
    { code: 'FAAA', description: 'Art & Architecture History' },
    { code: 'FAAM', description: 'Arts Management' },
    { code: 'FAAN', description: 'Analytics' },
    { code: 'FACC', description: 'Crit & Classic Lang & Cultures' },
    { code: 'FACD', description: 'Communication Design' },
    { code: 'FACM', description: 'Comparative Media Studies' },
    { code: 'FADE', description: 'Experience Design' },
    { code: 'FAEN', description: 'Energy' },
    { code: 'FAEP', description: 'Environ Principles & Practices' },
    { code: 'FAES', description: 'Environmental Science' },
    { code: 'FAET', description: 'Emerging Tech:Business&Design' },
    { code: 'FAFC', description: 'Film Studies' },
    { code: 'FAFN', description: 'Fashion' },
    { code: 'FAID', description: 'Interior Design' },
    { code: 'FAIM', description: 'Interactive Media Studies' },
    { code: 'FAJA', description: 'Music' },
    { code: 'FALR', description: 'History of Art & Architecture' },
    { code: 'FANC', description: 'Architecture' },
    { code: 'FANS', description: 'Neuroscience' },
    { code: 'FAPM', description: 'Premedical Studies' },
    { code: 'FAPT', description: 'Performance,Theatre & Practice' },
    { code: 'FASU', description: 'Sustainability' },
    { code: 'FATP', description: 'Theatre and Practice' },
    { code: 'FAZ1', description: 'Creative Arts - AA' },
    { code: 'FAZ4', description: 'Fine Arts - AA' },
    { code: 'FKC', description: 'Arts Management' },
    { code: 'FLC', description: 'Art with Certification' },
    { code: 'FNB', description: 'Music Theory & Composition' },
    { code: 'FND', description: 'Music Composition' },
    { code: 'FNM', description: 'Musicology' },
    { code: 'FNS', description: 'Music Education Supervision' },
    { code: 'FNT', description: 'Music Theory' },
    { code: 'IS76', description: 'Environmental Science' },
    { code: 'IS77', description: 'Environmental Studies' },
    { code: 'IS99', description: 'Interdisciplinary Studies' },
    { code: 'ISES', description: 'Environmental Science' },
    { code: 'ISZ8', description: 'Interdisciplinary Studies - AA' },
    { code: 'NC00', description: 'Non Credit' },
    { code: 'NC01', description: 'Non Credit ELC' },
    { code: 'RC08', description: 'Entrepreneurship' },
    { code: 'RC1C', description: 'Customer Service' },
    { code: 'RC2C', description: 'Manufacturing Foundations' },
    { code: 'RC48', description: 'Office Management Technology' },
    { code: 'RC49', description: 'Global & Intercultural Studies' },
    { code: 'RC50', description: 'Business Software Technology' },
    { code: 'RC53', description: 'Art Therapy' },
    { code: 'RC61', description: 'Food Systems and Food Studies' },
    { code: 'RC71', description: 'Nursing - 2 Year' },
    { code: 'RC87', description: 'Computer and Information Techn' },
    { code: 'RC88', description: 'Computer Technology' },
    { code: 'RCAB', description: 'Applied Biology' },
    { code: 'RCAM', description: 'Arts Management' },
    { code: 'RCAN', description: 'Analytics' },
    { code: 'RCCA', description: 'Community Arts' },
    { code: 'RCCC', description: 'Crit & Classic Lang & Cultures' },
    { code: 'RCCJ', description: 'Criminal Justice' },
    { code: 'RCCM', description: 'Comparative Media Studies' },
    { code: 'RCCR', description: 'Civic & Regional Development' },
    { code: 'RCCS', description: 'Communication Studies' },
    { code: 'RCDB', description: 'Digital Business Systems' },
    { code: 'RCDC', description: 'Digital Commerce' },
    { code: 'RCEB', description: 'E-Business Management Tech' },
    { code: 'RCEG', description: 'English Studies' },
    { code: 'RCEN', description: 'Energy' },
    { code: 'RCES', description: 'Environmental Science' },
    { code: 'RCET', description: 'Engineering Technology' },
    { code: 'RCFC', description: 'Film Studies' },
    { code: 'RCFI', description: 'Forensic Investigation' },
    { code: 'RCFN', description: 'Fashion' },
    { code: 'RCFS', description: 'Forensic Science' },
    { code: 'RCHC', description: 'Health Communication' },
    { code: 'RCHT', description: 'Health Information Technology' },
    { code: 'RCIM', description: 'Interactive Media Studies' },
    { code: 'RCIS', description: 'Integrative Studies' },
    { code: 'RCIT', description: 'Information Technology' },
    { code: 'RCK3', description: 'Marketing Management Tech' },
    { code: 'RCKA', description: 'Accounting Technology' },
    { code: 'RCKM', description: 'Business Management Technology' },
    { code: 'RCLS', description: 'Liberal Studies' },
    { code: 'RCN4', description: 'Nursing' },
    { code: 'RCNC', description: 'Nonprofit & Community Studies' },
    { code: 'RCNS', description: 'Neuroscience' },
    { code: 'RCPC', description: 'Mechanical Engineering Tech' },
    { code: 'RCPM', description: 'Premedical Studies' },
    { code: 'RCPR', description: 'Nursing - 4 Year' },
    { code: 'RCPS', description: 'Psychological Science' },
    { code: 'RCPZ', description: 'Electrical & Computer Eng Tech' },
    { code: 'RCSB', description: 'Small Business Management' },
    { code: 'RCSM', description: 'Sales Management' },
    { code: 'RCSR', description: 'Applied Social Research' },
    { code: 'RCSU', description: 'Sustainability' },
    { code: 'RCTS', description: 'Technical Study' },
    { code: 'RCU4', description: 'University Studies' },
    { code: 'RCZ1', description: 'Prof Studies & Appl Sci - AA' },
    { code: 'RCZ2', description: 'Liberal Arts & Appl Sci - AA' },
    { code: 'ZZZZ', description: 'Conversion' },
  ],
  status: 200,
  error: false,
};
module.exports = majorCodes;
